name: Ron Toekook
favicon: null
layout_spectrum: 0.5516412497963756
typography_spectrum: 0.05505611444823444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.15027512121014297
  lightness: 0.8726572026498616
  saturation: 0.9780261719133705
  rhythmicContrast: 0.4581319368444383
purpose: []
